### ISSUE TITLE
Doors didn't close after cycle

### ISSUE THREAD

**Issue by DavidPgl** [lizrad/fpspf#24]
- Doors didn't close between cycle 3 and 4
- Not sure if this is cycle related or just random

**Comment by DavidPgl** [comment]
Seems to happen when two enemies are alive and the ghost is killed first. When the real player is killed after that, the doors will already be open (happend cycle 4 and 5 for me)

**Comment by incredibleLeitman** [comment]
If a melee attack is spawned in the enemy base, it lasts longer than the reset and immediately kills newly created ghosts.

To prevent this, all pawns could be invicible during preperation cycle.
No or Go?

**Comment by AmonGruenwald** [comment]
go
