### ISSUE TITLE
Maybe use cumulative points instead of just the points from the last cycle

### ISSUE THREAD

**Issue by AmonGruenwald** [lizrad/fpspf#53]
doesn't feel that satisfying if you lead the whole round and then just easily loose in the last one because the enemy lands a lucky shot

**Comment by incredibleLeitman** [comment]
... or run in a "friendly" ghost shot :p

Yeah, fully support this!

**Comment by DavidPgl** [comment]
Added as optional toggle with 9a4200ef60875cb4db060b54c440425801b42fdc
