### ISSUE TITLE
Add new game mode for "remain captured" capture points

### ISSUE THREAD

**Issue by kb173** [lizrad/fpspf#72]
The game ends once a certain percentage of points (e.g. 50%) has been captured by one of the players.

Other than that, rounds remain the same, with a fixed time length.

**Comment by DavidPgl** [comment]
Switching between this mode and the "old" capturing mode is a bit tedious:
- HUD -> Hide progress bar and show progress cakes
- LevelManager -> Switch levels
- World -> Set required capture points to > 0.666... and < 1.0 to set it to 2 points

It should work otherwise(?), not much tested:P
